In [1]:
from time import time

import numpy as np
import torch

In [2]:
# ! Time Ms
time_ms_64 =lambda : np.int64(time()*10)
time_ms_16 =lambda : np.int16(time_ms_64()%1000)


# Numpy Random Seed

In [ ]:
# generate array of random numbers
arr = np.random.randn(3)
print(arr)

In [ ]:
#  ? Old Seeding mechanism
np.random.seed(3)
print(np.random.random(3))
print(np.random.random(3))
# [0.5507979  0.70814782 0.29090474]
# [0.51082761 0.89294695 0.89629309]

In [20]:
# ? another technique using old method
np.random.seed(time_ms_16())
print(np.random.random(3))
print(np.random.random(3))

[0.5382098  0.40213274 0.82456345]
[0.68398343 0.28952672 0.72297764]


In [32]:
# * New Seeding Mechanism
rand_seed = np.random.RandomState(time_ms_16())

print(rand_seed.randn(3))

[0.87744692 0.86095122 0.05184605]


# PyTorch Random Seed

In [35]:
torch.randn(5)

tensor([ 0.2831, -0.9588,  1.6768, -0.8105,  0.5861])

In [49]:
# Fix seeding
torch.manual_seed(15)
print(torch.randn(5))

tensor([-0.7056,  0.6741, -0.5454,  0.9107,  1.0682])


In [63]:
# dynamic seeding
torch.manual_seed(time_ms_16())
print(torch.randn(5))

tensor([ 1.0533,  1.1167,  0.2550, -1.2401,  1.2579])
