# Matrix Multiplication

In [ ]:
# imports
import numpy as np
import torch

## Numpy

In [ ]:
# create matrix
mat_1 = np.random.randn(2,3)
mat_2 = np.random.randn(3,4)
print(mat_1,end='\n\n\n')
print(mat_2,end='\n\n\n')
mat_mul = np.round(mat_1@mat_2, 2) #alternative way: np.matmul(mat_1, mat_2)
print(mat_mul)

## pyTorch

In [9]:
mat_a = torch.randn(3,3)
mat_b = torch.randn(3,6)
mat_c = torch.randn(5,3)
mat_c1 = torch.randn(7,3)

print(np.round(mat_a@mat_b,2))
print(np.round(mat_c@mat_c1.T,2))
print(np.round(mat_c1@mat_a,2))

tensor([[ 2.0000,  1.7200,  2.8700, -1.8000, -0.2200, -3.4500],
        [-0.7600,  0.1200, -0.8600, -0.4500,  0.5500,  2.7100],
        [ 0.9600,  2.4700,  0.1100, -2.4400,  0.0300,  2.7000]])
tensor([[-1.1300, -0.1800, -1.1200, -0.3600,  0.2300,  1.0100,  1.0400],
        [-0.7400,  0.1200, -1.3800,  0.5700,  0.7300,  0.6200,  1.1300],
        [-1.4600, -0.6200,  0.8300, -2.8700, -1.6300,  1.0300, -0.3300],
        [ 4.8100,  0.9200, -1.4700,  7.3200,  4.1000, -2.7200,  0.3000],
        [ 0.3900, -1.1300,  0.3100, -0.8400, -0.2600,  0.8000, -0.0900]])
tensor([[ 1.6300,  4.0300, -1.4500],
        [-1.1000, -0.5100,  0.6900],
        [ 3.0200,  0.4000, -0.3600],
        [-1.9400,  3.5400, -0.6300],
        [-1.7600,  1.8500, -0.3800],
        [-0.5700, -1.5200,  0.1300],
        [-2.3300, -0.7700,  0.3600]])
