In [5]:
#import libraries
import numpy as np
import torch

# NUMPY

In [2]:
# creating a vector
vec = np.array([ [1,2,3,4] ])
print(vec)

vec_2d = np.array([ ['a','b','c','d'], ['e','f','g','h'] ])
print(vec_2d)

NameError: name 'np' is not defined

## Transposing a vector using Numpy

In [14]:
t_vec = np.transpose(vec) # RETURNS TRANSPOSED COPY OF THE VECTOR USING np.transpose
print(t_vec)

print(vec.T) # RETURNS TRANSPOSED COPY OF THE VECTOR USING vector.T

[[1]
 [2]
 [3]
 [4]]
[[1]
 [2]
 [3]
 [4]]


## WORKING WITH 2D Matrix

In [15]:
transposed_vec_2d = vec_2d.T
print(transposed_vec_2d)

[['a' 'e']
 ['b' 'f']
 ['c' 'g']
 ['d' 'h']]


# pyTORCH

In [6]:
t_vec = torch.tensor([[1,2,3,4]])
t_vec_2d = torch.tensor([[1,2,3,4], [5,6,7,8] ])
print(t_vec)
print(t_vec_2d)

tensor([[1, 2, 3, 4]])
tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


## Transposing vector using pyTorch

In [7]:
print(t_vec.T)
print(t_vec_2d.T)

tensor([[1],
        [2],
        [3],
        [4]])
tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
