In [4]:
from time import time

import numpy as np
import torch

In [5]:
# generate array of random numbers
arr = np.random.randn(3)
print(arr)

[-0.36440123 -1.41734098  0.69240168]


In [13]:
#  ? Old Seeding mechanism
np.random.seed(3)
print(np.random.random(3))
print(np.random.random(3))
# [0.5507979  0.70814782 0.29090474]
# [0.51082761 0.89294695 0.89629309]

[0.5507979  0.70814782 0.29090474]
[0.51082761 0.89294695 0.89629309]


In [36]:
# ? another technique using old method
time_ms = np.int32(np.round(time()))
np.random.seed(time_ms)
print(np.random.random(3))
print(np.random.random(3))

[0.93819371 0.98501121 0.84603354]
[0.63501231 0.57092253 0.98939703]


In [ ]:
# * New Seeding Mechanism
